server:
  port: 0

spring:
  application:
    name: chatclient

chatapp:
  server:
    host: wss://${nginx.host:localhost}/${chatapp.domain:chatapp}/websocket

eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    preferIpAddress: true
#    ipAddress: 127.0.0.1
