server:
  port: 0

spring:
  application:
    name: chatapp

broker:
  relay:
    host: ${activemq.host:localhost}
    user: admin
    password: admin

logging:
  level:
    org.springframework.messaging: trace

eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    preferIpAddress: true
#    ipAddress: 127.0.0.1
